workdir: "100kb/"

#------ Simulation parameters ------
reference_length: 102400 # should ref_len always == query_len?
query_length: 102400 
match_count: 51 # (1024 / 2000) < 1 match per query file

#------ DREAM parameters ------
ibf_bins: 64
query_seg_count: 64
ibf_size: "50k"
cart_max_capacity: 2
max_queued_carts: 32

#------ Stellar parameters ------
num_matches: 100
sort_threshold: 101

#------ Evaluation parameters ------
repeat: 1
