workdir: "100kb/"

# simulation parameters
reference_length: 102400 # should ref_len always == query_len?
query_length: 102400 
match_count: 51 # (102400 / 2000) = 51 matches per query file

# stellar parameters
num_matches: 100
sort_threshold: 101

# evaluation parameters
repeat: 10
