workdir: "100Mb/"

#------ Simulation parameters ------
reference_length: 104857600 # should ref_len always == query_len?
query_length: 104857600
match_count: 52429 # (1024 / 2000) < 1 match per query file

#------ DREAM parameters ------
ibf_bins: 2048
cart_max_capacity: 5000
max_queued_carts: 4096

#------ Stellar parameters ------
num_matches: 53000
sort_threshold: 53001

#------ Evaluation parameters ------
repeat: 1
