workdir: "100Mb/"

#------ Simulation parameters ------
reference_length: 104857600 # should ref_len always == query_len?
query_length: 104857600
match_count: 52429 # (1024 / 2000) < 1 match per query file

#------ DREAM parameters ------
ibf_bins: 64
query_seg_count: 10000
ibf_size: "30M"
cart_max_capacity: 500
max_queued_carts: 64

#------ Stellar parameters ------
num_matches: 10000
sort_threshold: 10000

#------ Evaluation parameters ------
repeat: 1
