workdir: "1Mb/"

# simulation parameters
reference_length: 1048576 # should ref_len always == query_len?
query_length: 1048576 
match_count: 524 # (1048576 / 2000) = 524 matches per query file

# stellar parameters
num_matches: 700
sort_threshold: 701

# evaluation parameters
repeat: 1
