#---------------------------------
# List of bin names
#---------------------------------
bins: ../data/64/sample_bins

#---------------------------------
# Define a local match with: 
#    * minimum length
#    * maximum number of errors
#---------------------------------
min_length: 50
nr_errors: 1

#---------------------------------
# Sliding window algorithm parameters
#---------------------------------
kmer: 19
window: 23
pattern: 60
overlap: 0
size: 80m

