workdir: "out/"

#--------- Parameter to test --------
size_list: ["35M"]
# reference size is 83M

#--------- Simulation parameters --------
reference_length: 10000000
match_count: 512000 # per query file and error rate
haplotypes: 8
match_length: 150

#-------- Shared search parameters --------
ibf_bins: 64
er_rate: 0.05
minLen: 80

#-------- Valik parameters --------
window: 15
kmer_length: 13
pattern_overlap: [0, 10, 20, 30, 40, 49]

