workdir: "out/"

#--------- Parameter to test --------
size_list: ["1M", "5M", "10M", "15M", "20M", "25M", "30M", "35M", "40M", "45M", "50M", "55M", "60M"]
# reference size is 83M

#--------- Simulation parameters --------
reference_length: 10000000
match_count: 512000 # per query file and error rate
haplotypes: 8
match_length: 150

#-------- Shared search parameters --------
ibf_bins: 64
er_rate: 0.05
minLen: 80

#-------- Valik parameters --------
window: 15
kmer_length: 13
pattern_overlap: 49

