workdir: "100Mb/"

#--------- Simulation parameters --------
reference_length: 104857600
match_count: 512000 # per query file and error rate
ibf_bins: 64

#-------- Valik parameters --------
max_queued_carts: 64
max_cart_capacity: 6000
