workdir: "100Mb/"

#--------- Simulation parameters --------
reference_length: 100000000
match_count: 512000 # per query file and error rate
ibf_bins: 64

#-------- Shared search parameters --------
minLen: 100

#-------- Valik parameters --------
ibf_size: "25M"
pattern_overlap: 89
max_queued_carts: 64
max_cart_capacity: 6000
