workdir: "100Mb/"

#--------- Simulation parameters --------
reference_length: 100000000
match_count: 512000 # per query file and error rate
haplotypes: 8
match_length: 150

#-------- Shared search parameters --------
ibf_bins: 640
minLen: 50

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "400M"
pattern_overlap: 10

#-------- Evaluation parameters --------
repeat: 1
