workdir: "100Mb/"

#--------- Simulation parameters --------
reference_length: 100000000
match_count: 5120000 # per query file and error rate
haplotypes: 8
match_length: 150

#-------- Shared search parameters --------
ibf_bins: 640
minLen: 50

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "30M"
pattern_overlap: 10
thresh_tau: 0.75
thresh_pmax: 0.25

#-------- Stellar parameters --------
num_matches: 5120000
sort_threshold: 5120001

#-------- Evaluation parameters --------
repeat: 1
