workdir: "100Mb/"

#--------- Simulation parameters --------
reference_length: 100000000
match_count: 512000 # per query file and error rate
haplotypes: 8
match_length: 250

#-------- Shared search parameters --------
ibf_bins: 64
minLen: 100

#-------- Valik parameters --------
window: 17
kmer_length: 15
ibf_size: "250M"
pattern_overlap: 89

