workdir: "size/"

#--------- Parameter to test --------
size_list: ["10M", "30M", "50M", "70M", "90M", "110M"]

#--------- Simulation parameters --------
reference_length: 100000000
match_count: 5120000 # per query file and error rate
haplotypes: 8
match_length: 150

#-------- Shared search parameters --------
ibf_bins: 640
er_rate: 0.05
minLen: 80

#-------- Valik parameters --------
window: 15
kmer_length: 13
pattern_overlap: 49

