workdir: "100Mb/"

#--------- Simulation parameters --------
reference_length: 104857600
match_count: 524000 # per query file and error rate
match_length: 250
error_rate: 0.05

#-------- Shared search parameters --------
ibf_bins: 64
minLen: 100

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "20M"
pattern_overlap: 98

