workdir: "overlap_kmers/"

#--------- Parameter to test --------
pattern_overlap: [0, 10, 20, 30, 40, 45, 46, 47, 48, 49]

#--------- Simulation parameters --------
reference_length: 10000000
match_count: 512000 # per query file and error rate
haplotypes: 8
match_length: 150
sim_er_rate: 0.05

#-------- Shared search parameters --------
size_list: ["10M"] # reference size is 83M
ibf_bins: 64
minLen: 50

#-------- Valik parameters --------
window: 13
kmer_length: 13

