workdir: "1Mb/"

#------ Simulation parameters ------
reference_length: 1048576 # should ref_len always == query_len?
query_length: 1048576 
match_count: 524 # (1048576 / 2000) = 524 matches per query file

#------ Valik parameters ------
ibf_bins: 64
ibf_size: "500k"
query_seg_count: 64
cart_max_capacity: 10
max_queued_carts: 64

#------ Stellar parameters ------
num_matches: 700
sort_threshold: 701

#------ Evaluation parameters ------
repeat: 2

