workdir: "10Mb/"

# simulation parameters
reference_length: 10485760
query_length: 10485760

                     # 10485760 / 2000 = 5240 matches per query file
match_count: 1310    # 5240 / 4 = 1310 matches of each length

er_rates: ["0", "0025", "005", "0075", "01"] # manually change in simulate.sh

# stellar parameters
min_len: 50
num_matches: 7000
sort_threshold: 7001

# evaluation parameters
repeat: 1
min_overlap: 40
