workdir: "10Mb/"

#--------- Simulation parameters --------
reference_length: 10485760
match_count: 5120 # per query file and error rate
ibf_bins: 64

#-------- Valik parameters --------
max_cart_capacity: 100
max_queued_carts: 64

#-------- Evaluation parameters --------
repeat: 1
