workdir: "10Mb/"

#--------- Simulation parameters --------
reference_length: 10485760
match_count: 5120 # per query file and error rate
haplotypes: 1
match_length: 250

#-------- Shared search parameters --------
minLen: 100

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "5M"
pattern_overlap: 98

#-------- Evaluation parameters --------
repeat: 1
