workdir: "10Mb/"

#--------- Simulation parameters --------
reference_length: 10485760
match_count: 5120 # per query file and error rate
haplotypes: 4
match_length: 150

#-------- Shared search parameters --------
ibf_bins: 64
minLen: 50

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "3M"
pattern_overlap: 10
thresh_tau: 0.75
thresh_pmax: 0.25

#-------- Stellar parameters --------
num_matches: 7000
sort_threshold: 7001

#-------- Evaluation parameters --------
repeat: 1
