workdir: "10Mb/"

#--------- Simulation parameters --------
reference_length: 10485760
match_count: 5240 # per query file and error rate
match_length: 250
error_rate: 0.05

#-------- Shared search parameters --------
ibf_bins: 64
minLen: 100

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "4M"
pattern_overlap: 98

cart_max_capacity: 100
max_queued_carts: 32

