workdir: "100kb/"

#--------- Simulation parameters --------
reference_length: 102400
match_length: 250
match_count: 200 # per error rate
error_rate: 0.05

#-------- Shared search parameters --------
ibf_bins: 64
minLen: 100

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "2M"
pattern_overlap: 98

cart_max_capacity: 100
max_queued_carts: 1024

