workdir: "fly/"

#------ Simulation parameters ------
nr_matches: 25000

#------ Valik parameters ------
ibf_bins: 1024
window: 13
kmer_length: 11
ibf_size: "50M"
cart_max_capacity: 500
max_queued_carts: 64

#------ Evalutaion parameters ------
repeat: 2
