workdir: "2Gb/"

#--------- Simulation parameters --------
reference_length: 2000000000
match_count: 2048000 # per query file and error rate

#-------- Shared search parameters --------
ibf_bins: 1024
minLen: 80

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "2G"
pattern_overlap: 10
thresh_tau: 0.75
thresh_pmax: 0.75


# TODO: different number of matches for DREAM-Stellar (per bin) and Stellar (per ref)
#-------- Stellar parameters --------
num_matches: 2048000
sort_threshold: 2048001

#-------- Evaluation parameters --------
repeat: 1
