workdir: "4Gb/"

#--------- Simulation parameters --------
reference_length: 4000000000
match_count: 1638400
haplotypes: 1
match_length: 250

#-------- Shared search parameters --------
  #ibf_bins: 16384
  #ibf_bins: 1024
  #ibf_bins: 64
minLen: 100

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "2G" # 1/4th of the reference size
pattern_overlap: 98

