workdir: "4Gb/"

#--------- Simulation parameters --------
reference_length: 4294967296
match_count: 1703936
  #ibf_bins: 16384
  #ibf_bins: 1024
ibf_bins: 64

#-------- Valik parameters --------
ibf_size: "500M" # 1/4th of the reference size
max_queued_carts: 64
max_cart_capacity: 6000

