workdir: "4Gb/"

#--------- Simulation parameters --------
reference_length: 4000000000
match_count: 6553600
haplotypes: 8
match_length: 250

#-------- Shared search parameters --------
ibf_bins: 16384
minLen: 100

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "1G" # 1/8th of the reference size
pattern_overlap: 98

