workdir: "4Gb/"

#--------- Simulation parameters --------
reference_length: 500000000
match_count: 1703936
  # match_count: 1638400  old isn't divisible by 16384*8

  #ibf_bins: 16384
  #ibf_bins: 1024
ibf_bins: 64

#-------- Shared search parameters --------
minLen: 100

#-------- Valik parameters --------
ibf_size: "500M" # 1/4th of the reference size
max_queued_carts: 64
max_cart_capacity: 6000

