workdir: "4Gb/"

#--------- Simulation parameters --------
reference_length: 500000000
match_count: 1703936
  # match_count: 1638400  old isn't divisible by 16384*8
haplotypes: 8
match_length: 250

#-------- Shared search parameters --------
  #ibf_bins: 16384
  #ibf_bins: 1024
  #ibf_bins: 64
minLen: 100

#-------- Valik parameters --------
window: 17
kmer_length: 15
ibf_size: "500M" # 1/4th of the reference size
pattern_overlap: 98

