#-------- BLAST parameters --------

  # default

#evalues: [10]
#blast_kmer_lengths: [28]

  # l = 100
evalues: [10]
blast_kmer_lengths: [49, 32, 19]

  # l = 50
  #evalues: [1e-7, 1e-8, 1e-10]
  #blast_kmer_lengths: [28, 24, 16, 12]

