#-------- workflow parameters --------
valik_exec: "/group/ag_abi/evelina/valik/build/bin/valik"
workdir: "human"
stellar_out: "stellar"
blast_out: "blast"
dream_out: "dream"
lastz_out: "lastz"
last_out: "last"

#-------- input files --------
ref: "/srv/data/evelina/human/ref_concat.fa"
query: "/srv/data/evelina/mouse_query/masked.fa"
run_id: "human_vs_mouse"

#-------- Stellar search parameters --------
errors: [3]
min_len: [50]
min_overlap: [25]

