#-------- DREAM split parameters --------
ibf_fpr: [0.005]
ibf_bins: [2048]
valik_kmer_lengths: ["NA"]
  #valik_shapes: ["111101110111011111", "11111111011111111", "11101110101110111"]
  #valik_shapes: ["111101110111011111"]
valik_shapes: ["NA"]

#-------- DREAM build parameters --------
minimiser_flag: "--fast"
kmer_cmin: 0
kmer_cmax: [254]

#-------- DREAM search parameters --------
repeat_flag: "--keep-best-repeats"
repeat_periods: [1]
repeat_lengths: [1000]
bin_entropy_cutoffs: [0.75]
valik_thresh: ["NA"]

max_queued_carts: 2048
cart_max_capacity: 2000

