#-------- workflow parameters --------
valik_exec: "/group/ag_abi/evelina/valik/work_build/bin/dream-stellar"
workdir: "human"
stellar_out: "stellar"
dist_stellar_out: "dist_stellar"
blast_out: "blast_agrippina"
dream_out: "dream_agrippina"
lastz_out: "lastz"
last_out: "last_agrippina"

#-------- input files --------
ref: "/srv/data/evelina/human/ref_concat.fa"
query: "/srv/data/evelina/mouse/ref_concat.fa"
run_id: "human_vs_mouse"

#-------- Stellar search parameters --------
#errors: [4, 5, 6]
errors: [1, 2, 3, 4, 5, 6]
min_len: [100]
min_overlap: [50]

