#-------- DREAM split parameters --------
ibf_fpr: [0.005]
ibf_bins: [1024]
valik_kmer_lengths: [16]

#-------- DREAM build parameters --------
minimiser_flag: "--fast"
kmer_cmin: 0
kmer_cmax: [50, 150, 254]

#-------- DREAM search parameters --------
repeat_flag: "--keep-best-repeats"
repeat_periods: [1]
repeat_lengths: [1000]
  #bin_entropy_cutoffs: [0.25, 0.5, 0.75, 0.99]
bin_entropy_cutoffs: [0.25]
valik_thresh: [6, 9, 12, 15]

max_queued_carts: 1024
cart_max_capacity: 2000

