#-------- workflow parameters --------
valik_exec: "/group/ag_abi/evelina/valik/build/bin/valik"
workdir: "work"
stellar_out: "stellar_masked"
blast_out: "blast_masked"
dream_out: "dream_masked_k"
lastz_out: "lastz"

#-------- input files --------
ref: "/srv/data/evelina/mouse/ref_concat.fa"
query: "/srv/data/evelina/fly/query_concat.fa"
run_id: "mouse_vs_fly"

#-------- LASTZ parameters --------
#seed: ["12of19", "14of22", "1110100110010101111"]
lastz_seed: ["14of22", "111101001100101011111"]
