#-------- BLAST parameters --------

  # default
#evalues: [10]
# blast_kmer_lengths: [28]

  # l = 100
  #evalues: [1e-29]
  #blast_kmer_lengths: [51, 49, 45, 37, 33, 32, 29, 24, 21, 18, 16]

  # l = 50
evalues: [1e-7, 1e-8, 1e-10]
blast_kmer_lengths: [28, 24, 16, 12]

