#-------- DREAM split parameters --------
ibf_fpr: [0.005]
ibf_bins: [64, 128, 256, 512, 1024, 2048, 4096, 8192]
valik_kmer_lengths: [16]
valik_shapes: ["11111010010100110111111"]
  #valik_shapes: [, "1110100110010101111"]

#-------- DREAM build parameters --------
minimiser_flag: "--fast"
kmer_cmin: 0
kmer_cmax: [50]

#-------- DREAM search parameters --------
repeat_flag: "--keep-all-repeats"
repeat_periods: [1]
repeat_lengths: [1000]
bin_entropy_cutoffs: [1.0]
  #seg_count: 30000

valik_thresh: "N/A"

max_queued_carts: [64]
cart_max_capacity: [2000]

