#-------- workflow parameters --------
valik_exec: "/group/ag_abi/evelina/valik/build_seg/bin/valik"
workdir: "mouse"
stellar_out: "stellar"
blast_out: "blast"
dream_out: "dream_gapped"
lastz_out: "lastz"
last_out: "last"

#-------- input files --------
ref: "/srv/data/evelina/mouse/ref_concat.fa"
query: "/srv/data/evelina/fly/query_concat.fa"
run_id: "mouse_vs_fly"

#-------- Stellar search parameters --------
errors: [1, 3]
min_len: [50]
min_overlap: [25]

