#-------- workflow parameters --------
valik_exec: "/group/ag_abi/evelina/valik/work_build/bin/valik"
workdir: "work"
stellar_out: "stellar"
blast_out: "blast"
dream_out: "dream"
lastz_out: "lastz"
last_out: "last"

#-------- input files --------
ref: "/srv/data/evelina/mouse/ref_concat.fa"
query: "/srv/data/evelina/fly/query_concat.fa"
run_id: "mouse_vs_fly"

#-------- Stellar search parameters --------
errors: [1, 2, 3, 4, 5, 6]
min_len: [100]
min_overlap: [50]

