#-------- DREAM split parameters --------
ibf_fpr: 0.005
ibf_bins: [4096]
#valik_shapes: ["1111101010110101011111"]
#valik_shapes: ["1111011010110101101111"]
#valik_shapes: ["111101011010110101111"]
valik_shapes: ["11111010010100110111111"] # best from PatternHunter

#-------- DREAM build parameters --------
minimiser_flag: "--fast"
kmer_cmin: [0]
kmer_cmax: [254]

#-------- DREAM search parameters --------
repeat_flag: "--keep-all-repeats"
repeat_periods: [1]
repeat_lengths: [1000]
bin_entropy_cutoffs: [1.0]

max_queued_carts: 1024
cart_max_capacity: 1000

