workdir: "16GB/"

#--------- Simulation parameters --------
reference_length: 2000000000
match_count: 8192000 # per error rate
ibf_bins: 1024

#-------- Shared search parameters --------
minLen: 100

#-------- Valik parameters --------
ibf_size: "2G"
  #thresh_tau: 0.75
  #thresh_pmax: 0.5
max_queued_carts: 1024
max_cart_capacity: 6000
