workdir: "16GB/"

#--------- Simulation parameters --------
reference_length: 2000000000
match_count: 8192000 # per error rate
haplotypes: 8
match_length: 150

#-------- Shared search parameters --------
ibf_bins: 1024
minLen: 80

  # total size of reference bins: 16GB
  # TODO: increase (w, k) parameters to reduce spurious matches

#-------- Valik parameters --------
window: 15
kmer_length: 13
ibf_size: "1G"
pattern_overlap: 10
thresh_tau: 0.75
thresh_pmax: 0.5

#-------- Evaluation parameters --------
repeat: 1
