workdir: "10kb/"

# simulation parameters
reference_length: 10240 # should ref_len always == query_len?
query_length: 10240 
match_count: 5 # (10240 / 2000) = 5 matches per query file

# stellar parameters
num_matches: 100
sort_threshold: 101

# evaluation parameters
repeat: 10
