workdir: "10kb/"

#------ Simulation parameters ------
reference_length: 10240 # should ref_len always == query_len?
query_length: 10240 
match_count: 10 # (1024 / 2000) < 1 match per query file
error_rate: 0.05

#------ DREAM parameters ------
ibf_bins: 8
query_seg_count: 8
window: 15
kmer_length: 15
ibf_size: "5k"
cart_max_capacity: 1
max_queued_carts: 4

#------ Stellar parameters ------
num_matches: 50
sort_threshold: 51

#------ Evaluation parameters ------
repeat: 2
