workdir: "human/"

#------ Simulation parameters ------
reference_length: 3088269832 # ref len == query len
nr_matches: 50000

#------ Valik parameters ------
ibf_bins: 1024
window: 13
kmer_length: 11
ibf_size: "1500"
cart_max_capacity: 500
max_queued_carts: 64

#------ Evalutaion parameters ------
repeat: 1
