workdir: "human/"

#--------- Simulation parameters --------
reference_length: 3088269832
match_length: 250
match_count: 1703936 # per error rate
  #match_count: 170393 # per error rate
error_rate: 0.05

#-------- Shared search parameters --------
ibf_bins: 64
minLen: 100

#-------- Valik parameters --------
window: 17
kmer_length: 15
ibf_size: "1000m"
pattern_overlap: 98
cart_max_capacity: 80000
max_queued_carts: 20
