workdir: "1kb/"

#------ Simulation parameters ------
reference_length: 1024 # should ref_len always == query_len?
query_length: 1024 
match_count: 10 # (1024 / 2000) < 1 match per query file
error_rate: 0.05

#------ Valik parameters ------
ibf_bins: 8
query_seg_count: 8
window: 15
kmer_length: 15
ibf_size: "1k"
cart_max_capacity: 1
max_queued_carts: 4

#------ Evaluation parameters ------
repeat: 1
